#this file is now available in the submodule applicationsConfiguration UPDATED
#spring:
#  application:
#    name: api-gateway
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} #default to 'local' if not set
  cloud:
    config:
      allow-override: true #This allows the application to override properties from the config server
      override-none: false #This allows the application to override properties from the config server
      override-system-properties: false #This allows the application to override system properties from the config server
eureka:
  client:
    service-url:
      #make this dynamic so that it can be used in different environments
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8763/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


#there is no need to base-url for the api-gateway as it is a gateway and does not have its own base-url
#it is mainly used to route requests to other services. But if i need to create some endpoint in the
#api-gateway service for example to get its running status, i can set it here
#http://localhost:8080/swagger-ui/index.html#/inventory-controller/getAllInventory