spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ECommerce-Inventory-Service
    username: postgres
    password: postgres
api:
  redis:
    host: redis
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8763/eureka/}
