spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerce-Inventory-Service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
api:
  endpoint:
    base-url: /api/v1
#  inventory:
#    service:
#      base-url: http://inventory-service/api/v1/inventory
  redis:
    host: localhost
    port: 6379
          #port: 6000
          #timeout: 2000
        #cache-timeout: 3600
    cache-prefix: inventory-service
  cache:
    type: REDIS
  jackson:
    serialization:
      write-dates-as-timestamps: false #This ensures that dates are serialized as ISO-8601 formatted strings instead of Unix timestamps.
#Register with Eureka service discovery
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #this file is now available in the submodule applicationsConfiguration