spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerce-Inventory-Service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

api:
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8763/eureka/}