spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ECommerce-Product-Service
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} #default to 'local' if not set

  #new
  cloud:
    config:
      allow-override: true #This allows the application to override properties from the config server
      override-none: false #This allows the application to override properties from the config server
      override-system-properties: false #This allows the application to override system properties from the config server

  data:
    redis:
      host: ${REDIS_HOST:${SPRING_DATA_REDIS_HOST:redis}}
      port: ${REDIS_PORT:${SPRING_DATA_REDIS_PORT:6379}}
      database: 0 #default Redis database
      password: ${REDIS_PASSWORD:} #optional password, if Redis is secured, empty
      timeout: 5000 #5 seconds

api:
  endpoint:
    base-url: /api/v1
  redis:
    cache-prefix: product-service-${spring.profiles.active}
  cache:
    type: ${CACHE_TYPE:REDIS} #Allows catch type override
  jackson:
    serialization:
      write-dates-as-timestamps: false #This ensures that dates are serialized as ISO-8601 formatted strings instead of Unix timestamps.
    deserialization:
      fail-on-unknown-properties: false #This allows the application to ignore unknown properties in JSON requests, preventing deserialization errors.

#Register with Eureka service discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8763/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.cloud.config: DEBUG

  #state where you want to log info here
#  file:
#    name: logs/product-service.log #This will create a log file in the logs directory, which should be created in the root of the project
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    max-size: 10MB #Maximum size of the log file
#    max-history: 30 #Keep logs for 30 days



#this file is now available in the submodule applicationsConfiguration