spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ECommerce-Product-Service
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}


api:
  endpoint:
    base-url: /api/v1
  redis:
    cache-prefix: product-service
  cache:
    type: REDIS
  jackson:
    serialization:
      write-dates-as-timestamps: false #This ensures that dates are serialized as ISO-8601 formatted strings instead of Unix timestamps.
#Register with Eureka service discovery
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8762/eureka/
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8763/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#this file is now available in the submodule applicationsConfiguration