spring:
  #Runtime operations (reactive) database configuration using R2DBC
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/ECommerce-User-Service
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30000 #30 seconds
      max-acquire-time: 60000 #60 seconds

  #Schema migrations (blocking - start up only)
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ECommerce-User-Service
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  #reactive web application configuration
  main:
    web-application-type: reactive

  #active profile configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} #default to 'local' if not set

  #spring cloud config client configuration
  cloud:
    config:
      allow-override: true #This allows the application to override properties from the config server
      override-none: false #This allows the application to override properties from the config server
      override-system-properties: false #This allows the application to override system properties from the config server

  data:
    redis:
        host: ${REDIS_HOST:${SPRING_DATA_REDIS_HOST:localhost}}
        port: ${REDIS_PORT:${SPRING_DATA_REDIS_PORT:6379}}
        database: 0 #default Redis database
        password: ${REDIS_PASSWORD:} #optional password, if Redis is secured, empty
        timeout: 5000 #5 seconds
api:
  endpoint:
    base-url: /api/v1
  redis:
    cache-prefix: user-service-${spring.profiles.active}
  cache:
    type: ${CACHE_TYPE:REDIS} #Allows cache type override
  jackson:
    serialization:
      write-dates-as-timestamps: false #This ensures that dates are serialized as ISO-8601 formatted strings instead of Unix timestamps.
    deserialization:
      fail-on-unknown-properties: false #This allows the application to ignore unknown properties in JSON

#Register with Eureka service discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8763/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
